#!/bin/bash
while sleep 1
do
  if [ "`ifconfig | grep tun0`" != "" ]
  then
    echo "VPN | `uptime | cut -d ' ' -f 12 | cut -d ',' -f 1` | `date +%H:%M`"
  else
    echo "`uptime | cut -d ' ' -f 12 | cut -d ',' -f 1` | `date +%H:%M`"
  fi
done
