#!/bin/bash
echo 'July'
echo '----'
ledger -b '2016-07-01' -e '2016-08-01' -sf ~/accounting/ledger.dat balance

echo 'August'
echo '------'
ledger -b '2016-08-01' -e '2016-09-01' -sf ~/accounting/ledger.dat balance

echo 'Year'
echo '----'
ledger -b '2016-07-01' -sf ~/accounting/ledger.dat balance
